### ISSUE TITLE
Feature request: Config Function

### ISSUE THREAD

**Issue by Skye-31** [evanderkoogh/otel-cf-workers#1]
Following up from Discord, being able to define config similarly to [how vite does it](https://vitejs.dev/config/#conditional-config), via a function that takes `request` and `env` would be very useful!

**Comment by RichiCoder1** [comment]
@evanderkoogh this is supported, no? https://github.com/evanderkoogh/otel-cf-workers/blob/main/src/sdk.ts#L130

Might be worth updating the readme with isntructions on how to use this. Especially since I imagine using headers provided from `context.env` will be the default for most people.

**Comment by evanderkoogh** [comment]
I am in the middle of a massive refactor and that particular code hasn't been released yet, so I haven't updated the readme just yet.

But I will absolutely do when the code is stable again.

**Comment by evanderkoogh** [comment]
This is now in the latest “alpha” release 1.0.0-alpha.3. 

And way cooler than I expected, you can create a configuration for every single request, because you are passed the trigger for that request.
