### ISSUE TITLE
Broken with tax

### ISSUE THREAD

**Issue by jasonkuhrt** [evanderkoogh/otel-cf-workers#143]
When trying to run [`tsx`](https://tsx.is) on code that imports this library the following error happens:

```
/Users/jasonkuhrt/projects/prisma/pdp-control-plane/node_modules/.pnpm/@microlabs+otel-cf-workers@1.0.0-rc.39/node_modules/@microlabs/otel-cf-workers/src/spanprocessor.ts:4
import { Action, State, stateMachine } from 'ts-checked-fsm'
                        ^

SyntaxError: The requested module 'ts-checked-fsm' does not provide an export named 'stateMachine'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.12.2
```

It actually appears to be coming from Node.

I've bee looking at this and `ts-checked-fsm` package but do not see what the issue is yet.

**Comment by jasonkuhrt** [comment]
When I change the import to the following and log it:

```
import * as x from 'ts-checked-fsm';
```

I get:

`[Module: null prototype] { default: { stateMachine: [Function: n] } }`

so, its coming through as a default export, not a named export... hm 😕

**Comment by jahands** [comment]
Thanks for tracking this down! Should be fixed in `1.0.0-rc.40`

**Comment by jasonkuhrt** [comment]
Happy it helped!

**Comment by jasonkuhrt** [comment]
@jahands resolved the issue thanks!
