### ISSUE TITLE
trace.getActiveSpan() returning undefined in fetch

### ISSUE THREAD

**Issue by jasonkuhrt** [evanderkoogh/otel-cf-workers#149]
Hey,

I've got a setup sending traces to an OTEL collector.

In `fetch` handler however if I try `trace.getActiveSpan()` it returns undefined.

What could possibly be wrong leading to this? The docs examples looks simple without much in user land to cause it to not work.

**Comment by jasonkuhrt** [comment]
The issue is that I've installed the latest version of `@opentelemetry/api` and it is not the same as this library's version of `~1.6.0`.

I think this library should be using peer deps. Is there a reason it is not?

**Comment by nowfred** [comment]
> The issue is that I've installed the latest version of `@opentelemetry/api` and it is not the same as this library's version of `~1.6.0`.
> 
> I think this library should be using peer deps. Is there a reason it is not?

Thank you so much for following up on this, jason 'genius' kuhrt
