### ISSUE TITLE
Missing releases/changelogs for new versions

### ISSUE THREAD

**Issue by Cherry** [evanderkoogh/otel-cf-workers#154]
It seems the last version published on GitHub was `1.0.0-rc40` as per https://github.com/evanderkoogh/otel-cf-workers/releases

And the last change changelog entry is for `1.0.0-rc41`: https://github.com/evanderkoogh/otel-cf-workers/blob/main/CHANGELOG.md

But the latest version of npm is `1.0.0-rc43`. It looks like some of the recent versions were published manually perhaps, which may have broken the automation?

**Comment by jahands** [comment]
@evanderkoogh Be sure to add changesets for changes and then merge the “Version Packages” PR to bump the package version + publish to NPM. This is the release process we’ve been using, rather than doing these steps manually.

This ensures that the change log gets updated + GitHub releases get generated.

**Comment by evanderkoogh** [comment]
Oh yeah.. I totally missed that.. I noticed that I had forgotten to include the changeset in the PR, so did that on `main` and then published manually..
What is the "Version Packages" PR?

Also.. you have no idea how much I appreciate you lot looking after all this to the point where I screw things up as soon as I try to get back into things :)

**Comment by jahands** [comment]
Every time a commit lands on main, the [release](https://github.com/evanderkoogh/otel-cf-workers/blob/main/.github/workflows/release.yml) workflow runs. If there are new changesets, it will open a PR to version packages.

When we merge that PR (also to main), the same release workflow will detect that the current version in package.json has not been published and publish it + create a GitHub release.

If you forget to add a changeset in a Pr/commit, it’s totally fine to push a new commit with a changeset for the change.

This setup means we never have to update package.json or publish to NPM ourselves. It’s all managed by [changesets](https://github.com/changesets/changesets)

**Comment by evanderkoogh** [comment]
Ohh.. and I see. I released the version without actually merging the PR. So if I merge the PR, it will open a Version PR and if I merge that, all of the things are updated.

Awesome to know. I was on a call with someone while having them test things out, but I could have used the Github URL for the branch of that anyway.
