### ISSUE TITLE
Version RC44 is giving 400 bad request error

### ISSUE THREAD

**Issue by NejcZdovc** [evanderkoogh/otel-cf-workers#157]

**Comment by NejcZdovc** [comment]
I managed to fix this to reverting to version RC 41

**Comment by gdaszuta** [comment]
I am 99% sure this is related to changes in otlp-transformer after upgrade of opentelemetry-js and would be fixed by my MR https://github.com/evanderkoogh/otel-cf-workers/pull/156

**Comment by evanderkoogh** [comment]
I just merged your PR @gdaszuta and release `1.0.0-rc.45`.. If either of you could give that a go that would be great :)

**Comment by gdaszuta** [comment]
Tested, works for me perfectly fine. Thanks!

**Comment by evanderkoogh** [comment]
No, thank you for your fix :)
