### ISSUE TITLE
ESM interoperability question

### ISSUE THREAD

**Issue by oxcafedead** [evanderkoogh/otel-cf-workers#16]
Hi!
I am really not very experienced in JS/TS, especially in its complicated module systems.

However, I'd like to bring one concern here. I have issues in using this library for my ESM JavaScript project.
When I try to run unit tests using Mocha, after importing the library I get a runtime error, saying it cannot resolve one of the dependencies:
```
> npx mocha

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'xxx\node_modules\@microlabs\otel-cf-workers\dist\sampling' imported from xxx\node_modules\@microlabs\otel-cf-workers\dist\index.js        
    at new NodeError (node:internal/errors:393:5)
    at finalizeResolution (node:internal/modules/esm/resolve:323:11)
    at moduleResolve (node:internal/modules/esm/resolve:916:10)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
```
The reason is that `./dist` has `index.js` which contains CommonJS-compatible imports (without the `.js` extention) but it is not compatible with ESM. Most probably, TypeScript does some magic resolving modules w/o extensions. However, if we look at the guide for TypeScript,
https://www.typescriptlang.org/docs/handbook/esm-node.html
it mentions that either one should use ESM-compatible syntax:
```javascript
// ./bar.ts
import { helper } from "./foo.js"; // works in ESM & CJS
helper();
```
or have ESM & CommonJS separated by export index files at `package.json`:
```jsonc
...
"exports": {
        ".": {
            // Entry-point for `import "my-package"` in ESM
            "import": "./esm/index.js",
            // Entry-point for `require("my-package") in CJS
            "require": "./commonjs/index.cjs",
        },
    },
    // CJS fall-back for older versions of Node.js
    "main": "./commonjs/index.cjs",
...
```

Now, my question is, is it something which be introduced in this library?

I know that as a workaround, I can use some bundler and run my unit tests after building the code, but I guess my proposal may be a more "right" thing to do.

Apologize in advance, if this proposal contains some obvious errors or misunderstanding from my side.

Thanks for the great library!

**Comment by evanderkoogh** [comment]
Hey! I am absolutely no wizard in module systems either.

But you are absolutely correct in that I would like this to "just work" for everyone.. so certainly going to have a look to see what the best way forward is.

**Comment by evanderkoogh** [comment]
Ok.. so I have tried to follow the gist of all the module system wizards and it *looks* like it works now, but I would love for you to give this a go and check if that is indeed actually the case. It was released in `1.0.0-rc3`.

**Comment by oxcafedead** [comment]
@evanderkoogh Thanks for looking at this issue!
Can you please check your `index.js`? There are a couple of imports without `.js` left.

**Comment by jfsiii** [comment]
This "[Are the types wrong?](https://github.com/arethetypeswrong/arethetypeswrong.github.io)" tool is really helpful for types and more general package issues.

[It found](https://arethetypeswrong.github.io/?p=%40microlabs%2Fotel-cf-workers%401.0.0-rc.6) a few issues


<img width="368" alt="Screenshot 2023-07-19 at 11 12 06 AM" src="https://github.com/evanderkoogh/otel-cf-workers/assets/57655/8b8d47f9-4270-48af-9173-23e7f9078d6b">

You can also `npm pack` a local install and upload it to iterate on the changes. There's also [a CLI](https://github.com/arethetypeswrong/arethetypeswrong.github.io/tree/main/packages/cli)

**Comment by evanderkoogh** [comment]
Right.. 

So I just retested `1.0.0-rc.7` and it passed all of the things.

<img width="594" alt="Screenshot 2023-07-26 at 22 22 14" src="https://github.com/evanderkoogh/otel-cf-workers/assets/890386/2172472d-b935-4ed2-a099-021a31cbe6c2">

Can you let me know if this still happens?
