### ISSUE TITLE
Overly Complex Setup & Bugs

### ISSUE THREAD

**Issue by oldbettie** [evanderkoogh/otel-cf-workers#167]
I am sorry but this is annoyingly complex to figure out how to set it up... There is no actualy instructions on how to install the package and get it working anywhere online.

Here are the steps I have done so far.
- Create a new worker
- Install the packages from here https://www.npmjs.com/package/@microlabs/otel-cf-workers
- Install the otel api package
- Add `compatibility_flags = [ "nodejs_compat" ]` to my wrangler file
- Copy the following to `src/index.ts` file

```typescript
import { trace } from '@opentelemetry/api'
import { instrument, ResolveConfigFn } from '@microlabs/otel-cf-workers';


export interface Env {
	HONEYCOMB_API_KEY: string
	OTEL_TEST: KVNamespace
}

const handler = {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		await fetch('https://cloudflare.com')

		const greeting = "G'day World"
		trace.getActiveSpan()?.setAttribute('greeting', greeting)
		ctx.waitUntil(fetch('https://workers.dev'))
		return new Response(`${greeting}!`)
	},
}

const config: ResolveConfigFn = (env: Env, _trigger: any) => {
	return {
		exporter: {
			url: 'https://api.honeycomb.io/v1/traces',
			headers: { 'x-honeycomb-team': "key-here" },
		},
		service: { name: 'honeycomb-data-set' },
	}
}

export default instrument(handler, config)
```

I get an error stating that the pacakge is not installed `TS2307: Cannot find module @microlabs/otel-cf-workers or its corresponding type declarations.`

Even getting to this point was far more complex then it needs to be. How is there no basic setup instructions in a project with this many stars?

I have confirmed the package is installed correctly. I tried with both npm and pnpm. claude was no help either. 

I also tried import from here `import { instrument, ResolveConfigFn } from '@microlabs/otel-cf-workers/dist/esm/src';` which resolves my ide errors but run time errors still cause the same error saying the package dodes not exist.

**Comment by oldbettie** [comment]
I was able to come up with a part solution with `1.0.0-rc.45`

**Comment by evanderkoogh** [comment]
Hey @oldbettie, it is hard to overstate how lovely it is to have people a) complain about setup hassles and b) actually have them contribute the documentation they had wished to see :)

I made a few small alterations to your PR and pushed it up.. thanks!
