### ISSUE TITLE
RemixJS compatibility issues

### ISSUE THREAD

**Issue by tygern** [evanderkoogh/otel-cf-workers#17]
I see an error that looks like

```
service core:user:remix-cloudflare-workers: Uncaught ReferenceError: Buffer is not defined
```

when I add instrumentation to a Remix app. I've created [a minimal example to reproduce](https://github.com/tygern/buffer-issue). I see this error whether or not I use the `node_compat` flag in `wrangler.toml`. Any help would be appreciated.

**Comment by evanderkoogh** [comment]
First thank you for reminding me that I needed to add the `node_compat` flag to the README :)

I can't think of a good reason why Remix would include Buffer when you add the library? I will try to find some time later today to have a quick look at it. Thanks for creating that minimal repro.. Impossible to overstate how much of a difference that makes to people maintaining packages :)

**Comment by evanderkoogh** [comment]
Ugg.. this is an ugly hack by open-telemetry that we run into. They are using `/platform/node/*` & `/platform/browser/*` in certain packages and use the `package.json` `browser` field to overwrite the node version with the browser version.

The standard `wrangler` bundler probably picks the `browser` option, but Remix probably uses the `node` one.

If you can make that switch in Remix, that would be a (albeit shitty) workaround for now. I am going to have a think on how best to solve this seamlessly, so that things will work no matter what your bundler picks for you.

**Comment by evanderkoogh** [comment]
Hmm.. that fix was easier than I thought and slightly uglier than I had hoped.. 

Cloudflare Workers have a working implementation for `Buffer`, but it is not in the global scope, but after an import and setting it on the global scope, your repro worked.

Can you confirm that it works in your full example too?

**Comment by tygern** [comment]
Thanks for tracking that down so quickly! I'll check the fix out on our full codebase and let you know how it goes.

**Comment by tygern** [comment]
Sounds good. I agree with you that the issue is likely with how RemixJS is bundling. I'll do a bit of digging there and will reply with any findings.

**Comment by tygern** [comment]
Looks like there's a relatively new Remix issue regarding this https://github.com/remix-run/remix/issues/6715

**Comment by evanderkoogh** [comment]
That is indeed the issue you are seeing. Mark happens to be a friend of mine. I'll see if I can get in touch with him today or next week to have a chat about it :)

**Comment by evanderkoogh** [comment]
Ok.. had a long conversation with Mark about Remix and polyfills and how they can best handle this situation. The current plan is for you to have the ability to opt-into exactly the polyfills that you want. That should allow you to opt-out of the `async_hooks` polyfill.

He will be keeping the issue on the Remix side updated with a PR and progress once there is more to share.

**Comment by tygern** [comment]
Sounds like a good solution. Glad you’re well connected 😄

**Comment by tygern** [comment]
Looks like the fix in https://github.com/remix-run/remix/pull/6814 gets things working for us. We've updated the [buffer-issue](https://github.com/tygern/buffer-issue) repo to use the nightly mentioned in the PR. The one clunky bit is that opentelemetry requires `child_process` to build, which is [one of the unimplemented polyfills](https://github.com/remix-run/remix/blob/84281d9e881253a86157a4fa6b8a256aa0850b59/packages/remix-dev/compiler/server/compiler.ts#L82) excluded from the Remix build by default. This means that we have to configure Remix to add `child_processes` and [several other polyfills](https://github.com/tygern/buffer-issue/blob/main/remix.config.js#L14-L26) to the build.

**Comment by evanderkoogh** [comment]
Well.. good to see that the fix works at least. But I am quite surprised that opentelemetry requires all these Node dependencies?! Would be worth investigating where that goes wrong. If I grab the buffer-issue repo and remove the polyfills, that should make it fail in the way that you saw right?

**Comment by tygern** [comment]
We were surprised too! Yes, if you set `serverNodeBuiltinsPolyfill: true` in the buffer-issue repo you'll see an error about `child_process` being missing when running `npm run build`. Once you add `serverNodeBuiltinsPolyfill: ['child_process']` you'll see a bunch of other errors for missing node libraries on build.

**Comment by tygern** [comment]
Looks like the 1.19.0 Remix release fixes this issue. I'll close for now. I appreciate your help!
