### ISSUE TITLE
Add support for HTTP server and client metrics

### ISSUE THREAD

**Issue by stebet** [evanderkoogh/otel-cf-workers#180]
It'd be awesome if support for HTTP server/client metrics could be added to the OTel Pipeline as well to track worker request processing time (maybe a flag indicating if we'd want the entire worker wall time or just the time it took to handle a request and return a response) and the same for outbound fetch requests:

https://opentelemetry.io/docs/specs/semconv/http/http-metrics/

**Comment by evanderkoogh** [comment]
Hey @stebet, while in theory it might be possible to add those metrics, in practice that is a bit tougher than it might seem, but more importantly they would not be very useful. Unless you have a massive amount of traffic, or extremely localised clients, your requests will be so spread out over different machines that you will get basically one datapoint per request.

You are better off using a service that can calculate those metrics based on the traces that we do enable. I know Honeycomb is able to do that, but there might be others too..
