### ISSUE TITLE
how do you add custom log info for queue handler?

### ISSUE THREAD

**Issue by alexdoan102** [evanderkoogh/otel-cf-workers#2]
how do you add custom log info for queue handler?

![image](https://github.com/evanderkoogh/otel-cf-workers/assets/73307/2006a170-80c5-46eb-9fcf-161bd884d604)

**Comment by evanderkoogh** [comment]
You should be able to get the current span by called `trace.getActiveSpan()`

Have a look at the example at: https://github.com/evanderkoogh/otel-cf-workers/blob/34700b4e6ca021a24c75150de44f9900f36e187c/examples/worker/src/index.ts#LL32C2-L32C59
