### ISSUE TITLE
includeTraceContext is always set to true despite override

### ISSUE THREAD

**Issue by rtbenfield** [evanderkoogh/otel-cf-workers#23]
It seems that despite overriding `fetch.includeTraceContext` in the config function, the `traceparent` header is always set on outgoing fetch calls.

I tracked this down to [this line](https://github.com/evanderkoogh/otel-cf-workers/blob/6d78a576fa157fd090335e3105859e0de20e0672/src/sdk.ts#L110) in `parseConfig` that uses `|| true` rather than `?? true` to coalesce the value. It also appears that retrieving this value [here](https://github.com/evanderkoogh/otel-cf-workers/blob/6d78a576fa157fd090335e3105859e0de20e0672/src/instrumentation/fetch.ts#L177) in `instrumentFetcher` does not invoke the function, resulting in the value always being truthy for function use cases.

I'm happy to raise a PR to address these two spots if you're open to contributions 🙂 

Thanks for publishing this library. The automatic instrumentation of Cloudflare bindings is well done 🥇

**Comment by evanderkoogh** [comment]
I would *love* PRs. I am really looking to make this a project that can work even when I don’t have as much time to work on.

It is too important for the ecosystem to let things slip 😉

**Comment by rtbenfield** [comment]
Awesome! I can also share my use case here in case anyone comes across this issue with a similar one.

We have a Worker that receives an HTTP request generated by our users. That HTTP request _may_ have a `traceparent` header from their app's instrumentation. We then do some work with that request and forward it to another system, but need to preserve the _original_ `traceparent` value that we received. We use otel-cf-workers to capture traces from within our Worker, but need to essentially disable the context tracking from external requests in or out. The automatic instrumentation is currently overriding the `traceparent` of the outbound request.

With #24, we will be able to either disable the outbound trace context completely _or_ intelligently with a snippet like:
```ts
const config: ResolveConfigFn = (env: Env, trigger) => {
  return {
    exporter: {
      // ...
    },
    fetch: {
      includeTraceContext(request) {
        // disable context propagation if the request has an existing traceparent
        return !request.headers.has("traceparent");
      }
    },
    service: {
      // ...
    },
  }
}
```

**Comment by evanderkoogh** [comment]
Thanks for the PR.. that is greatly appreciated :)
