### ISSUE TITLE
does this library off the same context.trace.fetch 

### ISSUE THREAD

**Issue by alexdoan102** [evanderkoogh/otel-cf-workers#3]
does this library off the same context.trace.fetch as the original library [workers-honeycomb-logger] ???

I need to wrap the 'fetch" calls  (https://ross-hagan.com/blog/remix-cloudflare-and-honeycomb)
![image](https://github.com/evanderkoogh/otel-cf-workers/assets/73307/5f96de43-8983-4e4a-9f84-e5fcc53b9561)

**Comment by evanderkoogh** [comment]
One of the main selling points of creating this library based on the OTel spec and the new AsyncLocal functionality in the Workers is that we don't need to treat `fetch` any differently. Just use the regular `fetch` and the traces will automatically show up :)
