### ISSUE TITLE
Missing passThroughOnException on ExecutionContext

### ISSUE THREAD

**Issue by jfsiii** [evanderkoogh/otel-cf-workers#34]
The `ctx` argument passed to `fetch` is missing [`passThroughOnException` ](https://developers.cloudflare.com/workers/runtime-apis/fetch-event#passthroughonexception)

When I add this logging inside the `instrument`ed `fetch` handler (e.g. [here](https://github.com/evanderkoogh/otel-cf-workers/blob/4a89752c5ceecdd3d3aae39f447dd0e96879a8bd/examples/worker/src/handler.ts#L18) or [here](https://github.com/tygern/remix-otel-issue/blob/99f0d5f9b8ae4f0673456c56a584d7fb27bcdc62/server.ts#L25C14-L25C14)):

```js
console.log('handler.fetch ctx', ctx, 'waitUntil?', ctx.waitUntil, 'passThroughOnException?', ctx.passThroughOnException)
```

I see
```
handler.fetch ctx Proxy(ExecutionContext) waitUntil? Proxy(Function) passThroughOnException? undefined
```

I also didn't see any references to `passThroughOnException` in this repo. Perhaps it's intentional, but I believe it's expected/required.

**Comment by evanderkoogh** [comment]
You are absolutely correct that that should be present. I forgot to add the "if not any of the properties I want to proxy, pass the request through to the actual ExecutionContext object" :)

Fix is commit and hopefully will have time to roll out a new release later tonight :)
