### ISSUE TITLE
Support for custom propagators?

### ISSUE THREAD

**Issue by plantfansam** [evanderkoogh/otel-cf-workers#38]
Hi! I am interested in first-classing support for custom propagators. As I read it, you cannot specify this in the config, as [the library hard-codes a w3c propagator here](https://github.com/evanderkoogh/otel-cf-workers/blob/6b19cfe415cf9b0bd952700f00a0e562b60bc307/src/sdk.ts#L73).  A couple questions, then:

- Am I right that there's no way to explicitly configure this in the library?
- If I'm right, would you be open to a patch that adds support? I'd be happy to contribute.

**Comment by evanderkoogh** [comment]
Hey mate.. apologies, I completely missed this when you posted it. The short answer is yes to both :)
