### ISSUE TITLE
wrangler 3.7 gives error:  [ Could not resolve "node:async_hooks" ]

### ISSUE THREAD

**Issue by alexdoan102** [evanderkoogh/otel-cf-workers#49]
for wrangler 3.7, and  the wrangler.toml values are:

compatibility_date = "2023-08-21"
node_compat = true

![image](https://github.com/evanderkoogh/otel-cf-workers/assets/73307/6cfee012-3fff-48e1-b3f8-6f308b67f7ea)

**Comment by alexdoan102** [comment]
nvm...this i needed to use the other compatibility_flags = [ "nodejs_compat" ]

**Comment by evanderkoogh** [comment]
Need to make this more clear in the documentation :)

**Comment by alexdoan102** [comment]
@evanderkoogh  this still does not work.  (the fetch is not being called at all)

![image](https://github.com/evanderkoogh/otel-cf-workers/assets/73307/2f2b12cf-521b-4519-bca4-f2a93b312561)
