### ISSUE TITLE
for wrangler 3.7, the trace API call is not working

### ISSUE THREAD

**Issue by alexdoan102** [evanderkoogh/otel-cf-workers#50]
the trace API is not called on the fetch
 ==> is not returning success or failure, and it seem like the fetch is not called at all.

      ==>     BTW, if make the same request via POSTMAN, it works.  (with the same body)

![image](https://github.com/evanderkoogh/otel-cf-workers/assets/73307/f9186404-d547-4b33-b065-af5391583e0c)

**Comment by alexdoan102** [comment]
i found a workaround but not sure why you have to call the unwrap<> twice..
 => if you unwrap twice, the traceAPI is called correclty

![image](https://github.com/evanderkoogh/otel-cf-workers/assets/73307/f6d15e76-c5df-4193-b042-4174d4188474)

**Comment by evanderkoogh** [comment]
There was a bug with the `wrap` function in `rc.9` that I fixed in `rc.10`. Could you check if this also solved this issue?
