### ISSUE TITLE
Service worker syntax

### ISSUE THREAD

**Issue by aivLuk** [evanderkoogh/otel-cf-workers#51]
More of a question than an issue, does it work with service worker syntax?

```
addEventListener('fetch', event => {
  event.respondWith(new Response('Hello'));
});
```

If so, could there be an example on how it should be implemented?

**Comment by evanderkoogh** [comment]
Hey.. 

It currently does not support it and it is pretty far down my list of things to want to build.

having said that I would be more than happy to accept a PR if someone wants to add support for it.
