### ISSUE TITLE
Systematize and document release process

### ISSUE THREAD

**Issue by plantfansam** [evanderkoogh/otel-cf-workers#52]
As a package consumer, it would be nice to have:

- A [GitHub action](https://github.com/features/actions) that publishes a release with the tag from package.json
- [GitHub releases](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) for all releases
- Git tags on the commit corresponding to a given release
- Docs on release process

I'd be happy to contribute a PR to do this.

**Comment by evanderkoogh** [comment]
Yes! I will be eternally grateful for at least days, if not weeks if you gimme a PR for that 😄

**Comment by evanderkoogh** [comment]
Hey @plantfansam, I am just going through the issues to see what is left to get to the big 1.0. I would love to get this done before that if you have the time to make it happen?

**Comment by plantfansam** [comment]
Probably! When's the big 1.0?

**Comment by evanderkoogh** [comment]
I don’t really have a time frame. Basically when I can stamp out the remaining bug(s). Hopefully later this week, early next week? But rather flexible.

Prefer to have everything in place proper than to prematurely release something that isn’t ready yet..

**Comment by evanderkoogh** [comment]
Just added a git pre-commit hook that runs prettier on the changed files, so that we at least won't run into any format issues.

**Comment by jahands** [comment]
We now have CI checks and changeset-based releases 🎉
