### ISSUE TITLE
for wrangler 3.7, the trace API call is not working  (still not working

### ISSUE THREAD

**Issue by alexdoan102** [evanderkoogh/otel-cf-workers#54]
related to same is https://github.com/evanderkoogh/otel-cf-workers/issues/50
==> this is not fixed

please see my last comment on this ticket,.

**Comment by evanderkoogh** [comment]
Hey.. it sounds like the waitUntil isn't working properly and that is why it is cut off. 

Could you give me a bit more info about what kind of request you are doing?

**Comment by evanderkoogh** [comment]
Hey @alexdoan102.. I think I found the issue with traces not exporting properly. I have tried to fix this in `1.0.0-rc.12`. Would you be able to give that a go and see if that fixes your issues?

**Comment by alexdoan102** [comment]
@evanderkoogh  version [1.0.0-rc.13] works !!!   All is good.
=> thanks for fixing this.

**Comment by evanderkoogh** [comment]
Awesome to hear! And sorry about the inconvenience..
