### ISSUE TITLE
Update opentelemetry-js semantic conventions which differ from spec

### ISSUE THREAD

**Issue by rdooley** [evanderkoogh/otel-cf-workers#62]
A few notes here about opentelemetry-js SemanticConventions we are using that differ from spec
- `http.request_content_length` should be `http.request.body.size`
- `http.status_code` should be `http.response.status_code`
- `http.scheme` should be `url.scheme`
- `http.user_agent` should be `user-agent.original`

_Originally posted by @rdooley in https://github.com/evanderkoogh/otel-cf-workers/issues/53#issuecomment-1728495110_

**Comment by evanderkoogh** [comment]
Am I understanding you correctly that we are using the constants in opentelemetry-js, but that those are not the right ones according to the spec?!

**Comment by rdooley** [comment]
yes

**Comment by evanderkoogh** [comment]
I fixed all of those in https://github.com/evanderkoogh/otel-cf-workers/commit/819e313476aca1c9e37f8987dd54b31bdeced6a4
