### ISSUE TITLE
Nested `waitUntil` not correctly awaited

### ISSUE THREAD

**Issue by hansottowirtz** [evanderkoogh/otel-cf-workers#7]
Due to this line I believe nested `waitUntil`s are not correctly awaited:

https://github.com/evanderkoogh/otel-cf-workers/blob/9b40f78e8a84b34fa31e8db1d26013c0844f74ed/src/instrumentation/common.ts#L22-L24

It's exactly the same issue as here:
https://github.com/cloudflare/miniflare/issues/605

I'll open a PR implementing [this code](https://github.com/bubblydoo/wait-until-generalized/blob/main/src/all-settled-mutable.ts).

**Comment by evanderkoogh** [comment]
Doh!

awesome catch! I am hot on the tail of a fix for the wrangler 3 issue so once I fixed that I’ll merge this and get a release out. Thanks!
