### ISSUE TITLE
The global tracer is not of type WorkerTracer and can not export spans

### ISSUE THREAD

**Issue by fforres** [evanderkoogh/otel-cf-workers#75]
Hey folks! I keep on seeing the following issue pop up on a project I'm building.

With the most basic setup, I see the following on my logs:
`"The global tracer is not of type WorkerTracer and can not export spans"`

This is our current PR.  https://github.com/JSConfCL/gql_api/pull/94
(Even if I comment any parts related to `getActiveSpan` or setting span attributes, the issue persists. It's triggered by the addition of the `instrument` function that wraps everything. 🤔 

Not entirely sure if I'm making something wrong, but would love any pointers in the right direction 🙏

**Comment by evanderkoogh** [comment]
Hmm.. at first blush you aren’t doing anything wrong? So I will try to have a bit of a better look later today.

**Comment by fforres** [comment]
Appreciate it! If there's anything I can do to help, LMK 🙏 Have the project running on a cloudflare worker if it helps 🙏 (Or to sync on a call, etc)

**Comment by evanderkoogh** [comment]
Haven’t had a chance to look at it in-depth, but would you be able to isolate the problem in a sample repo with just one worker that fails? That would be amazing!
