### ISSUE TITLE
[Question] Support for sending traces to other tracing backends/vendors?

### ISSUE THREAD

**Issue by adnanrahic** [evanderkoogh/otel-cf-workers#80]
Hi!

I love the lib! 🙌 

I used it to set up Wrangler local testing and integration testing with OpenTelemetry traces.
I am having some issues setting up the trace exporter for the tracing backends/vendors I'm using in prod.

It works great with Honeycomb!

Wanted to ask if you have any pointers or guides on how to set up other vendors?
I'm seemingly using the same config as with Honeycomb, but the trace exporter fails with strange errors.

**Sample Error 1**
Here's the error when I use Grafana Cloud:

```
(log) Error sending spans to exporter: ReferenceError: XMLHttpRequest is not defined
```

Grafana Cloud exporter options:

```
const options = {
    url: 'https://otlp-gateway-prod-us-central-0.grafana.net/otlp',
    headers: { 'Authorization': 'Basic <base64 user:token' },
}
```

**Sample Error 2**
Here's the error when I use Tracetest:

```
(debug) sendBeacon - can send {"resourceSpans":[{ <redacted> }]}
```

Tracetest exporter options:

```
const options = {
    url: 'https://agent-<token>.tracetest.io:4318/v1/traces',
}
```

Is there anything specific with the Honeycomb config I can replicate for the other ones I'm using? 🤔 

Thanks! Awesome product! Excited to see it grow. 🔥

**Comment by johndistasio** [comment]
For whatever it's worth, I was able to use this library out of the box with HyperDX. I'm using version `1.0.0-rc.15`.

**Comment by adnanrahic** [comment]
I managed to figure out that the underlying JavaScript lib for the OpenTelemetry exporter using OTLP HTTP does not support custom ports when using TLS (`https`) endpoints.

This might be the main issue why I was seeing this issue. I will try again and see if I can reproduce it.

**Comment by RichiCoder1** [comment]
Cloudflare workers doesn't allow you to fetch against a non-default port. You'd need to use [Origin rules](https://developers.cloudflare.com/rules/origin-rules/features/#destination-port) to support that case.

**Comment by jahands** [comment]
This library already supports sending to multiple providers. For example, here's Axiom.co's docs: https://axiom.co/docs/guides/opentelemetry-cloudflare-workers
